-- Migration 015: Add soul_hash and soul_version columns, populate from persona files
-- This makes persona invocation fully operational (soul validation requires these)

BEGIN;

-- Add soul_hash column if missing
ALTER TABLE personas ADD COLUMN IF NOT EXISTS soul_hash VARCHAR(64);
COMMENT ON COLUMN personas.soul_hash IS 'SHA-256 hash of persona soul file for integrity validation';

-- Add soul_version column if missing
ALTER TABLE personas ADD COLUMN IF NOT EXISTS soul_version INTEGER DEFAULT 1;
COMMENT ON COLUMN personas.soul_version IS 'Version counter for soul file updates';

-- Populate soul hashes from known values (generated by npm run init-hashes)
UPDATE personas SET soul_hash = hashes.hash, soul_version = 1
FROM (VALUES
    ('pessoa',      '37ab0645b7a06c6e20286290633e6b35f2b3f8feb8adf8d66843b4c87506edeb'),
    ('caeiro',      '5391674808a24d7f519a8852612294d10c2add252dbec5f5d3ea4902be4c1b5f'),
    ('reis',        '3eb26432538e83607ef2336a2ee8e3ebafa49f02f0d1e753909bf381340994df'),
    ('campos',      '2bece368eef21741c905d95c2ce6889c68a4ea307eaa006285c39fc36822a98a'),
    ('soares',      'c4dbb7ef3211c8eeba42b5092ed57a781e236dd38308d49fe7fc8df258610448'),
    ('hegel',       'a28138e52a0778d0b3ea9fd4c0a4cb292a7bd2ffca822ae22387a2460050df2f'),
    ('socrates',    'dc8ab1b645867c152d8f6a41abde1c12f123395823ea8dfdf09916070bf985ed'),
    ('diogenes',    '24feab81cff4acf5966228c4f1bcfb451e477e916c84c761c348f80e137e03cd'),
    ('moore',       '306c82d02f4db98d0af3c137893c889f663589d98ad729ccd6abaf48e9676171'),
    ('dee',         '6ec28733ce7e4d3a76acb7b1fa71ca0d9f26539f38361fa68f517c707d7c7354'),
    ('crowley',     '9cc34d850e46476a39ee5ed1d76c5f28994d1454f899840c9d5b90d5a3e1c074'),
    ('choronzon',   '26428d743c1d4138a121773ec4e6b41a48273d3624205c123f4708d4a10c5e62'),
    ('tesla',       '93db535ef70f3fbb3dc959e1f2dd855715fbe821fa91e5d0fee7c5f0f774b9f8'),
    ('feynman',     '8ce8f5ae94366d06e055fbadcf8fc715ee8f8965beb43ee4c11d0f8557f33a69'),
    ('lovelace',    '4a234a0dd3aa8c5a88c13c3a2d620acaea49cfa0ce97d4655b10a30eb9a9ec4f'),
    ('vito',        'd370544bd7c9956099bffb7fb0426d8f8a2da56b82cd96fdcbaa0433bdaa71c2'),
    ('michael',     '86ebab8c9368857cb858fc99ba3ef6c1123b91c8479aadc31a71d104be823c3e'),
    ('suntzu',      '9e9dd183507ae17ff47d163716406e25b3e798158220a9856877151735d91b76'),
    ('machiavelli', '4866fc0458a1c45bd7ff465581820f0babfa45765a681cca768759b806949b4c'),
    ('hermes',      '5e84a94fbebc254bbe650ac2417add0b3e1c5d43c7e270363c50e142439c1a91'),
    ('prometheus',  'd5658c0fc2160ed8c8db33e11f76e8406d35482a946efb5efab6152a84a14d37'),
    ('cassandra',   '3948187138086d54b665c0bfedf10602d13f4a97137aafcc4c3a0699aff2d277'),
    ('nalvage',     '59c5c854728c58e7027858ef52f1d5a93638b613a241c5abd4eb44eaac64aa07'),
    ('ave',         '364b11a73c6e58e0947bf0d108914f55b8691cc90025646f860044c4dc3300fe'),
    ('madimi',      'a2a96af6499d1e072ad45f5de5f5809a9a845ed7506cadbe94ac4dc19bbc24b3')
) AS hashes(name, hash)
WHERE personas.name = hashes.name;

-- Verify all 25 personas have hashes
DO $$
DECLARE
    missing INTEGER;
BEGIN
    SELECT COUNT(*) INTO missing FROM personas WHERE soul_hash IS NULL;
    IF missing > 0 THEN
        RAISE WARNING 'Migration 015: % personas still missing soul_hash', missing;
    ELSE
        RAISE NOTICE 'Migration 015: All 25 personas have soul_hash populated';
    END IF;
END $$;

COMMIT;
